### ISSUE TITLE
Rotation when flying a looping

### ISSUE THREAD

**Issue by TrickShotMLG02** [yasirkula/UnityBezierSolution#15]
I am using your asset for a flight path. But when I want to fly a looping, the plane rotates when flying straigth up and also when flying straight down. Is there any possibility to fly a looping overhead?

**Comment by yasirkula** [comment]
Probably caused by Quaternion.LookRotation's upwards parameter always pointing up. Perhaps changing [this line](https://github.com/yasirkula/UnityBezierSolution/blob/2c4d164de81104cecee946f0469d0fd3124a2924/Plugins/BezierSolution/Utilities/BezierWalkerWithSpeed.cs#L59) as follows would work:

```csharp
{
	Quaternion _rotation1 = Quaternion.LookRotation( spline.GetTangent( m_normalizedT ), Vector3.up );
	Quaternion _rotation2 = Quaternion.LookRotation( spline.GetTangent( m_normalizedT ), Vector3.down );
	
	targetRotation = Quaternion.Angle( _rotation1, transform.rotation ) < Quaternion.Angle( _rotation2, transform.rotation ) ? _rotation1 : _rotation2;
}
```

Alternatively, you can use the bezier points' Extra Data property to tell whether or not the plane should be upwards or downwards at a section of the spline. At the upper section of the loop, bezier points' Extra Data would have a negative component:

![ss](https://user-images.githubusercontent.com/10211608/80690493-8ad46b00-8ad7-11ea-81b0-67cbc99dc35d.png)

Inside the BezierWalker script, if this value is negative, we can use Vector3.down as upwards parameter:

```csharp
targetRotation = Quaternion.LookRotation( spline.GetTangent( m_normalizedT ), spline.GetExtraData( m_normalizedT ).x >= 0 ? Vector3.up : Vector3.down );
```

**Comment by TrickShotMLG02** [comment]
Thank you very much for your fast reply. Everything works well now

Great work, keep it up!
