### ISSUE TITLE
 Velocity Control

### ISSUE THREAD

**Issue by TaynaCT** [yasirkula/UnityBezierSolution#6]
Hey there,
First of all, great job. It's an awesome tool.

But I have two questions. First, there is a way to implement some speed modifiers end using Bezier Walker With Time?

Second, how can I hide the line from the camera? I tried to change the layer but is drawing on the GUI, I was not able to find the settings of this.

Best regards,
Tayna Tinoco

**Comment by yasirkula** [comment]
The only way to change the speed in Bezier Walker With Time would be to change the Travel Time value.

To hide the runtime gizmos, you can deselect Draw Runtime Gizmos from the spline's Inspector.

**Comment by TaynaCT** [comment]
Thank you very much for the enlightenment.

**Comment by jackbrookes** [comment]
I am interested in adding capabilities for velocity control, and pauses. I am happy to help & contribute to the repo. Do you have any suggestions?

My thoughts were, one of:

* Change the Speed value to a curve (in `BezierWalkerWithSpeed`), and sample from this curve with normalised time
* Allow a speed curve to be set per-node with something like the "extra data", or as a new component which can be attached to a node
* Add an event system to the nodes, so when passing a node an event is called and a method can be executed. Users can write methods which modify speed.

None of these are great to me because when modifying the speed there's a chance the framerate affects the total distance travelled. Ideally each node would be associated directly with a time point to avoid this issue.

**Comment by yasirkula** [comment]
You can use an AnimationCurve or enter the speed values to "extra data" and use spline.GetExtraData to interpolate between these values, yes. In the past, I've thought about calling an event each time an end point was passed but didn't actually try to implement it.

As you said, all these options are affected by framerate. It is not possible to replicate the behaviour of Unity's Timeline with BezierSolution when traveling along the spline with constant speed because the "traveling with speed" algorithm isn't deterministic, it is only a fast approximation. For example, calling MoveAlongSpline two times with deltaMovement=1 will probably return a slightly different result than calling MoveAlongSpline once with deltaMovement=2.
